-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 10:37:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema anpr_metrics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anpr_metrics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anpr_metrics` DEFAULT CHARACTER SET utf8 ;
USE `anpr_metrics` ;

-- -----------------------------------------------------
-- Table `anpr_metrics`.`projectdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anpr_metrics`.`projectdata` (
  `user` VARCHAR(90) NOT NULL,
  `project` VARCHAR(90) NOT NULL,
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`user`, `project`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `anpr_metrics`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anpr_metrics`.`projects` (
  `user` VARCHAR(90) NOT NULL,
  `project` VARCHAR(90) NOT NULL,
  `openIssues` INT(11) NULL DEFAULT NULL,
  `avgClosedHoursTime` VARCHAR(45) NULL DEFAULT NULL,
  `avgFirstAnswerTime` VARCHAR(45) NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user`, `project`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
